# Phase1: Data Engineering

In [1]:
from pathlib import Path
import pandas as pd

In [4]:
us_stock_list.head()

      代码                               名称      secid
0      A                              安捷伦      106.A
1     AA                             美国铝业     106.AA
2   AACB      Artius II Acquisition Inc-A   105.AACB
3  AACBR     Artius II Acquisition Inc Rt  105.AACBR
4  AACBU  Artius II Acquisition Inc Unit   105.AACBU

In [6]:
ROOT = Path.home() / "Desktop" / "Data" / "Equities" / '在市股票' / 'A.csv'
A = pd.read_csv(ROOT)

In [7]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6572 entries, 0 to 6571
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6572 non-null   int64
 1   DateTime    6572 non-null   object
 2   Open        6572 non-null   float64
 3   High        6572 non-null   float64
 4   Low         6572 non-null   float64
 5   Close       6572 non-null   float64
 6   Volume      6572 non-null   int64
dtypes: float64(4), int64(2), object(1)
memory usage: 359.5+ KB

In [8]:
A.head()

   Unnamed: 0    DateTime     Open     High      Low    Close   Volume
0           0  2000-01-04  68.1250  68.8750  64.7500  66.5000  3408500
1           1  2000-01-05  66.2500  66.5000  60.3125  62.3750  4119200
2           2  2000-01-06  61.6250  62.0000  58.1250  60.0000  1812900
3           3  2000-01-07  59.0625  65.9375  59.0000  65.0000  2016900
4           4  2000-01-10  69.0000  69.6250  67.5625  68.9375  1536800